### ISSUE TITLE
[Issue] Unprecedented Installation Error 

### ISSUE THREAD

**Issue by hiteshhedwig** [mcuadros/go-rpi-rgb-led-matrix#19]
Hi,
I was trying to install the binding. It throws an error as mentioned in the readme. But not the same. 

```
# github.com/mcuadros/go-rpi-rgb-led-matrix
../../../work/pkg/mod/github.com/mcuadros/go-rpi-rgb-led-matrix@v0.0.0-20180401002551-b26063b3169a/matrix.go:6:10: fatal error: led-matrix-c.h: No such file or directory
 #include <led-matrix-c.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
```

How should i deal with it ? 

`go env` 

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/username/.cache/go-build"
GOENV="/home/username/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/username/work/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/username/work"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/username/gocv_work/src/rgbtest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build058517942=/tmp/go-build -gno-record-gcc-switches"
```

Any guidance?

**Comment by NelsonFrancisco** [comment]
Same. Can anyone help?

go env:

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/username/.cache/go-build"
GOENV="/home/username/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/username/.asdf/installs/golang/1.16.6/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/username/.asdf/installs/golang/1.16.6/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/username/.asdf/installs/golang/1.16.6/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/username/.asdf/installs/golang/1.16.6/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1790760651=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by hiteshhedwig** [comment]
Yes, try using  [this instead ](https://github.com/RockKeeper/go-rpi-rgb-led-matrix ). It worked well in my case. Not to brag but i have written this [blog](https://hiteshhedwig.github.io/hedwig_explains/2021/08/08/golang-rgbmatrix/) to document what i was doing. Hopefully this helps you. Let me know if you encounter any error.

**Comment by NelsonFrancisco** [comment]
It works, thanks.

This library looks like an incomplete wrapper over original rpi-rgb-led-matrix. It looks like it does not have the equivalent of `rgb_matrix::DrawText` for example.

**Comment by hiteshhedwig** [comment]
No. Library is well complete. Incase you want to draw text. You will have to implement it considering it as an image. See [this](https://github.com/hiteshhedwig/go-rpi-rgb-led-matrix/blob/master/examples/text/main.go). It may help you. Toolkit provided in repo is very helpful to understand the basic working. Hopefully, it helps.

**Comment by NelsonFrancisco** [comment]
This is offtopic, but do you know a font that both: 
- supports unicode characters like weather icons
- looks good on a LED display. With no flickering leds because of these "gradient" pixels. For example, the "grey" pixels in these characters
![Selection_002](https://user-images.githubusercontent.com/31771519/136551409-b15c8ef7-dff5-438a-a477-7685bfc93b1e.png)
