### ISSUE TITLE
Install fails.

### ISSUE THREAD

**Issue by borud** [mcuadros/go-rpi-rgb-led-matrix#2]
Followed the instructions on the in README.md but got this:

    borud@raspberrypi:~/gocode/src/github.com/mcuadros/go-rpi-rgb-led-matrix $ go install -v ./...
    matrix.go: malformed #cgo argument: -I${SRCDIR}/vendor/rpi-rgb-led-matrix/include
    examples/basic/main.go:8:2: /home/borud/gocode/src/github.com/mcuadros/go-rpi-rgb-led-matrix/matrix.go: malformed #cgo argument: -I${SRCDIR}/vendor/rpi-rgb-led-matrix/include

**Comment by mcuadros** [comment]
which version of go are you running?

**Comment by borud** [comment]
Sorry for the late reply.  I can't reach the machine right now, but I was running the latest version of Raspian released on 2016-11-25 with whatever the latest Go version was that Apt will install on a Raspberry Pi 3 Model B.

I'll try to remember updating this when I get back home :-)

**Comment by mcuadros** [comment]
fill free to read when you have more info. thanks
