### ISSUE TITLE
Crashes when not run as root

### ISSUE THREAD

**Issue by lukasmalkmus** [mcuadros/go-rpi-rgb-led-matrix#4]
The library panics when not run as root, because the `rip-rgb-led-matrix` needs to do some low-level stuff which requires root access. Instead of panicing, it might be better to recover and return an error in `NewRGBLedMatrix()`.

**Comment by mcuadros** [comment]
Yep, it requires root privileges since it write directly in `/dev/mem`. Yep, will be nice handle the panic.

**Comment by lukasmalkmus** [comment]
I have quickly opened #5. I made the small change in the GitHub editor because I can't access my dev env at the moment.

**Comment by lukasmalkmus** [comment]
#5 was merged
