### ISSUE TITLE
2 panels 32x64 - which are the correct parameters?

### ISSUE THREAD

**Issue by marcinguy** [mcuadros/go-rpi-rgb-led-matrix#8]
Got little bit confused with program parameters, so with 2 panels 32x64 I have to pass:

go run main.go -image mariosmall.gif -led-chain 2 -led-parallel 2 -led-rows 32

is this correct?

Thanks,

**Comment by mcuadros** [comment]
Depends on your configuration but you can read the correct values at:
https://github.com/hzeller/rpi-rgb-led-matrix#types-of-displays
